### ISSUE TITLE
Crash on unknown code

### ISSUE THREAD

**Issue by CoderPlusPlus** [adamhb123/EasyHIDListen#1]
When a key is pressed that does not exist in the list of keys, the application crashes.  I think it would be better to display the hex code and a message that it's an unsupported key.  

Also, you might consider supporting 0xB0 and 0xC1 (FAKE_01 and FAKE_18, respectively).  I know they were deprecated, but they still exist in the firmware, so if a keyboard generates one of those codes naturally (like mine), they are still sent and cause the crash.  Soarer has been MIA for years, so I don't think they're ever getting removed from the firmware.  

My Zenith Turbosport keyboard has an Fn key that used to control the system's built in harware features.  One of those Fn keys is Fn+F3 which outputs 0xB0.  When I try this combination, EasyHIDListen crashes.  So maybe have it say something like "code=B0 translation=FAKE_01 [deprecated]" so that the user knows it's a deprecated key, but can make their own decision on whether to use it and the application is able to continue without error.

This is a very useful program!  It's making remapping the keys from my Zenith Turbosport keyboard MUCH faster.  Thank you for taking the time to write it!

**Comment by adamhb123** [comment]
Working on a hotfix release as we speak. I have no way to test the changes so if you can get back to me once v1.2 is released I would appreciate it!

**Comment by CoderPlusPlus** [comment]
That fixed it!  It now reports:

`PRESS   ||      code=B0 translation=FAKE_01`

Thanks!
